# Generated by Django 5.2.4 on 2025-07-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('ci', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('nuevo', 'NUEVO'), ('usado', 'USADO')], default='nuevo', max_length=5)),
                ('unidades', models.PositiveBigIntegerField(blank=True, null=True)),
                ('kilometros', models.PositiveBigIntegerField(blank=True, null=True)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concesionario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reparacion', models.DateField()),
                ('horas_trabajo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.coche')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.mecanico')),
            ],
        ),
    ]
