# Generated by Django 5.2.4 on 2025-07-13 12:22

import concesionario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[concesionario.validators.salario_minimo]),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='fecha_reparacion',
            field=models.DateField(validators=[concesionario.validators.fecha_reparacion]),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='horas_trabajo',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[concesionario.validators.horas_trabajadas]),
        ),
    ]
